function hB = plugin_board()
% Board definition

%   Copyright 2015 The MathWorks, Inc.

% Construct board object
hB = hdlcoder.Board;

hB.BoardName    = 'Altera Cyclone V DE0-Nano-SoC';     % Name shown in HDL Workflow Advisor

% FPGA device information
hB.FPGAVendor   = 'Altera';
hB.FPGAFamily   = 'Cyclone V';
hB.FPGADevice   = '5CSEMA4U23C6';
hB.FPGAPackage  = '';%'UFBGA';
hB.FPGASpeed    = '';%'6';

% Tool information
hB.SupportedTool = {'Altera QUARTUS II'};

% FPGA JTAG chain position
hB.JTAGChainPosition = 2;

%% Add interfaces
% Custom board external I/O interface
hB.addExternalIOInterface( ...
    'InterfaceID',    'Green LEDs', ...
    'InterfaceType',  'OUT', ...
    'PortName',       'LED', ...
    'PortWidth',      8, ...
    'FPGAPin',        {'W15', 'AA24', 'V16', 'V15', ...
                        'AF26', 'AE26', 'Y16', 'AA23'}, ...  
    'IOPadConstraint', {'IO_STANDARD "3.3-V LVTTL"'} );
 
hB.addExternalIOInterface( ...
    'InterfaceID',    'Slide Switches', ...
    'InterfaceType',  'IN', ...
    'PortName',       'SW', ...
    'PortWidth',      4, ...
    'FPGAPin',        {'L10', 'L9', 'H6', 'H5'}, ... 
    'IOPadConstraint', {'IO_STANDARD "3.3-V LVTTL"'} );

hB.addExternalIOInterface( ...
    'InterfaceID',    'Push Buttons', ...
    'InterfaceType',  'IN', ...
    'PortName',       'KEY', ...
    'PortWidth',      2, ...
    'FPGAPin',        {'AH17', 'AH16'}, ...
    'IOPadConstraint', {'IO_STANDARD "3.3-V LVTTL"'} );

hB.addExternalIOInterface( ...
    'InterfaceID',    'Clock Interface', ...
    'InterfaceType',  'IN', ...
    'PortName',       'FPGA_CLK1_50', ...
    'PortWidth',      1, ...
    'FPGAPin',        {'V11'}, ...
    'IOPadConstraint', {'IO_STANDARD "3.3-V LVTTL"'} );





