-- -------------------------------------------------------------
-- 
-- File Name: C:\Users\d57w762\Desktop\lab4\hdlsrc\hdlcoder_led_blinking_4bit\led_count_ip_rdfifo_data_classic_ram_16x32b.vhd
-- Created: 2017-03-07 12:53:51
-- 
-- Generated by MATLAB 9.0 and HDL Coder 3.8
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: led_count_ip_rdfifo_data_classic_ram_16x32b
-- Source Path: led_count_ip/led_count_ip_axi4/led_count_ip_axi4_module/led_count_ip_rdfifo_data/led_count_ip_rdfifo_data_classic/led_count_ip_rdfifo_data_classic_ram_16x32b
-- Hierarchy Level: 5
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY led_count_ip_rdfifo_data_classic_ram_16x32b IS
  PORT( clk                               :   IN    std_logic;
        enb                               :   IN    std_logic;
        wr_din                            :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        wr_addr                           :   IN    std_logic_vector(3 DOWNTO 0);  -- ufix4
        wr_en                             :   IN    std_logic;  -- ufix1
        rd_addr                           :   IN    std_logic_vector(3 DOWNTO 0);  -- ufix4
        rd_dout                           :   OUT   std_logic_vector(31 DOWNTO 0)  -- ufix32
        );
END led_count_ip_rdfifo_data_classic_ram_16x32b;


ARCHITECTURE rtl OF led_count_ip_rdfifo_data_classic_ram_16x32b IS

  -- Component Declarations
  COMPONENT led_count_ip_SimpleDualPortRAM_16x32b
    PORT( clk                             :   IN    std_logic;
          enb                             :   IN    std_logic;
          wr_din                          :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          wr_addr                         :   IN    std_logic_vector(3 DOWNTO 0);  -- ufix4
          wr_en                           :   IN    std_logic;  -- ufix1
          rd_addr                         :   IN    std_logic_vector(3 DOWNTO 0);  -- ufix4
          rd_dout                         :   OUT   std_logic_vector(31 DOWNTO 0)  -- ufix32
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : led_count_ip_SimpleDualPortRAM_16x32b
    USE ENTITY work.led_count_ip_SimpleDualPortRAM_16x32b(rtl);

  -- Signals
  SIGNAL rd_dout_tmp                      : std_logic_vector(31 DOWNTO 0);  -- ufix32

BEGIN
  u_led_count_ip_SimpleDualPortRAM_16x32b : led_count_ip_SimpleDualPortRAM_16x32b
    PORT MAP( clk => clk,
              enb => enb,
              wr_din => wr_din,  -- ufix32
              wr_addr => wr_addr,  -- ufix4
              wr_en => wr_en,  -- ufix1
              rd_addr => rd_addr,  -- ufix4
              rd_dout => rd_dout_tmp  -- ufix32
              );

  rd_dout <= rd_dout_tmp;

END rtl;

