-- -------------------------------------------------------------
-- 
-- File Name: C:\Users\d57w762\Desktop\lab4\hdlsrc\hdlcoder_led_blinking_4bit\led_count_ip_dut.vhd
-- Created: 2017-03-07 12:53:51
-- 
-- Generated by MATLAB 9.0 and HDL Coder 3.8
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: led_count_ip_dut
-- Source Path: led_count_ip/led_count_ip_dut
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY led_count_ip_dut IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        dut_enable                        :   IN    std_logic;  -- ufix1
        Blink_frequency                   :   IN    std_logic_vector(3 DOWNTO 0);  -- ufix4
        Blink_direction                   :   IN    std_logic;  -- ufix1
        ce_out                            :   OUT   std_logic;  -- ufix1
        LED                               :   OUT   std_logic_vector(3 DOWNTO 0);  -- ufix4
        Read_back                         :   OUT   std_logic_vector(7 DOWNTO 0)  -- ufix8
        );
END led_count_ip_dut;


ARCHITECTURE rtl OF led_count_ip_dut IS

  -- Component Declarations
  COMPONENT led_count_ip_src_led_counter
    PORT( clk                             :   IN    std_logic;
          clk_enable                      :   IN    std_logic;
          reset                           :   IN    std_logic;
          Blink_frequency                 :   IN    std_logic_vector(3 DOWNTO 0);  -- ufix4
          Blink_direction                 :   IN    std_logic;  -- ufix1
          ce_out                          :   OUT   std_logic;  -- ufix1
          LED                             :   OUT   std_logic_vector(3 DOWNTO 0);  -- ufix4
          Read_back                       :   OUT   std_logic_vector(7 DOWNTO 0)  -- ufix8
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : led_count_ip_src_led_counter
    USE ENTITY work.led_count_ip_src_led_counter(rtl);

  -- Signals
  SIGNAL enb                              : std_logic;
  SIGNAL Blink_direction_sig              : std_logic;  -- ufix1
  SIGNAL ce_out_sig                       : std_logic;  -- ufix1
  SIGNAL LED_sig                          : std_logic_vector(3 DOWNTO 0);  -- ufix4
  SIGNAL Read_back_sig                    : std_logic_vector(7 DOWNTO 0);  -- ufix8

BEGIN
  u_led_count_ip_src_led_counter : led_count_ip_src_led_counter
    PORT MAP( clk => clk,
              clk_enable => enb,
              reset => reset,
              Blink_frequency => Blink_frequency,  -- ufix4
              Blink_direction => Blink_direction_sig,  -- ufix1
              ce_out => ce_out_sig,  -- ufix1
              LED => LED_sig,  -- ufix4
              Read_back => Read_back_sig  -- ufix8
              );

  Blink_direction_sig <= Blink_direction;

  enb <= dut_enable;

  ce_out <= ce_out_sig;

  LED <= LED_sig;

  Read_back <= Read_back_sig;

END rtl;

