// system_soc_mm_interconnect_0.v

// This file was auto-generated from altera_mm_interconnect_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 16.0 211

`timescale 1 ps / 1 ps
module system_soc_mm_interconnect_0 (
		input  wire [11:0] hps_0_h2f_axi_master_awid,                            //                           hps_0_h2f_axi_master.awid
		input  wire [29:0] hps_0_h2f_axi_master_awaddr,                          //                                               .awaddr
		input  wire [3:0]  hps_0_h2f_axi_master_awlen,                           //                                               .awlen
		input  wire [2:0]  hps_0_h2f_axi_master_awsize,                          //                                               .awsize
		input  wire [1:0]  hps_0_h2f_axi_master_awburst,                         //                                               .awburst
		input  wire [1:0]  hps_0_h2f_axi_master_awlock,                          //                                               .awlock
		input  wire [3:0]  hps_0_h2f_axi_master_awcache,                         //                                               .awcache
		input  wire [2:0]  hps_0_h2f_axi_master_awprot,                          //                                               .awprot
		input  wire        hps_0_h2f_axi_master_awvalid,                         //                                               .awvalid
		output wire        hps_0_h2f_axi_master_awready,                         //                                               .awready
		input  wire [11:0] hps_0_h2f_axi_master_wid,                             //                                               .wid
		input  wire [31:0] hps_0_h2f_axi_master_wdata,                           //                                               .wdata
		input  wire [3:0]  hps_0_h2f_axi_master_wstrb,                           //                                               .wstrb
		input  wire        hps_0_h2f_axi_master_wlast,                           //                                               .wlast
		input  wire        hps_0_h2f_axi_master_wvalid,                          //                                               .wvalid
		output wire        hps_0_h2f_axi_master_wready,                          //                                               .wready
		output wire [11:0] hps_0_h2f_axi_master_bid,                             //                                               .bid
		output wire [1:0]  hps_0_h2f_axi_master_bresp,                           //                                               .bresp
		output wire        hps_0_h2f_axi_master_bvalid,                          //                                               .bvalid
		input  wire        hps_0_h2f_axi_master_bready,                          //                                               .bready
		input  wire [11:0] hps_0_h2f_axi_master_arid,                            //                                               .arid
		input  wire [29:0] hps_0_h2f_axi_master_araddr,                          //                                               .araddr
		input  wire [3:0]  hps_0_h2f_axi_master_arlen,                           //                                               .arlen
		input  wire [2:0]  hps_0_h2f_axi_master_arsize,                          //                                               .arsize
		input  wire [1:0]  hps_0_h2f_axi_master_arburst,                         //                                               .arburst
		input  wire [1:0]  hps_0_h2f_axi_master_arlock,                          //                                               .arlock
		input  wire [3:0]  hps_0_h2f_axi_master_arcache,                         //                                               .arcache
		input  wire [2:0]  hps_0_h2f_axi_master_arprot,                          //                                               .arprot
		input  wire        hps_0_h2f_axi_master_arvalid,                         //                                               .arvalid
		output wire        hps_0_h2f_axi_master_arready,                         //                                               .arready
		output wire [11:0] hps_0_h2f_axi_master_rid,                             //                                               .rid
		output wire [31:0] hps_0_h2f_axi_master_rdata,                           //                                               .rdata
		output wire [1:0]  hps_0_h2f_axi_master_rresp,                           //                                               .rresp
		output wire        hps_0_h2f_axi_master_rlast,                           //                                               .rlast
		output wire        hps_0_h2f_axi_master_rvalid,                          //                                               .rvalid
		input  wire        hps_0_h2f_axi_master_rready,                          //                                               .rready
		output wire [11:0] led_count_ip_0_s_axi_awid,                            //                           led_count_ip_0_s_axi.awid
		output wire [15:0] led_count_ip_0_s_axi_awaddr,                          //                                               .awaddr
		output wire [7:0]  led_count_ip_0_s_axi_awlen,                           //                                               .awlen
		output wire [2:0]  led_count_ip_0_s_axi_awsize,                          //                                               .awsize
		output wire [1:0]  led_count_ip_0_s_axi_awburst,                         //                                               .awburst
		output wire [0:0]  led_count_ip_0_s_axi_awlock,                          //                                               .awlock
		output wire [3:0]  led_count_ip_0_s_axi_awcache,                         //                                               .awcache
		output wire [2:0]  led_count_ip_0_s_axi_awprot,                          //                                               .awprot
		output wire        led_count_ip_0_s_axi_awvalid,                         //                                               .awvalid
		input  wire        led_count_ip_0_s_axi_awready,                         //                                               .awready
		output wire [31:0] led_count_ip_0_s_axi_wdata,                           //                                               .wdata
		output wire [3:0]  led_count_ip_0_s_axi_wstrb,                           //                                               .wstrb
		output wire        led_count_ip_0_s_axi_wlast,                           //                                               .wlast
		output wire        led_count_ip_0_s_axi_wvalid,                          //                                               .wvalid
		input  wire        led_count_ip_0_s_axi_wready,                          //                                               .wready
		input  wire [11:0] led_count_ip_0_s_axi_bid,                             //                                               .bid
		input  wire [1:0]  led_count_ip_0_s_axi_bresp,                           //                                               .bresp
		input  wire        led_count_ip_0_s_axi_bvalid,                          //                                               .bvalid
		output wire        led_count_ip_0_s_axi_bready,                          //                                               .bready
		output wire [11:0] led_count_ip_0_s_axi_arid,                            //                                               .arid
		output wire [15:0] led_count_ip_0_s_axi_araddr,                          //                                               .araddr
		output wire [7:0]  led_count_ip_0_s_axi_arlen,                           //                                               .arlen
		output wire [2:0]  led_count_ip_0_s_axi_arsize,                          //                                               .arsize
		output wire [1:0]  led_count_ip_0_s_axi_arburst,                         //                                               .arburst
		output wire [0:0]  led_count_ip_0_s_axi_arlock,                          //                                               .arlock
		output wire [3:0]  led_count_ip_0_s_axi_arcache,                         //                                               .arcache
		output wire [2:0]  led_count_ip_0_s_axi_arprot,                          //                                               .arprot
		output wire        led_count_ip_0_s_axi_arvalid,                         //                                               .arvalid
		input  wire        led_count_ip_0_s_axi_arready,                         //                                               .arready
		input  wire [11:0] led_count_ip_0_s_axi_rid,                             //                                               .rid
		input  wire [31:0] led_count_ip_0_s_axi_rdata,                           //                                               .rdata
		input  wire [1:0]  led_count_ip_0_s_axi_rresp,                           //                                               .rresp
		input  wire        led_count_ip_0_s_axi_rlast,                           //                                               .rlast
		input  wire        led_count_ip_0_s_axi_rvalid,                          //                                               .rvalid
		output wire        led_count_ip_0_s_axi_rready,                          //                                               .rready
		input  wire        pll_0_outclk0_clk,                                    //                                  pll_0_outclk0.clk
		input  wire        led_count_ip_0_axi_reset_reset_bridge_in_reset_reset  // led_count_ip_0_axi_reset_reset_bridge_in_reset.reset
	);

	wire   [0:0] hps_0_h2f_axi_master_id_pad_m0_ruser;    // led_count_ip_0_s_axi_translator:s0_ruser -> hps_0_h2f_axi_master_id_pad:m0_ruser
	wire   [0:0] hps_0_h2f_axi_master_id_pad_m0_wuser;    // hps_0_h2f_axi_master_id_pad:m0_wuser -> led_count_ip_0_s_axi_translator:s0_wuser
	wire   [1:0] hps_0_h2f_axi_master_id_pad_m0_awburst;  // hps_0_h2f_axi_master_id_pad:m0_awburst -> led_count_ip_0_s_axi_translator:s0_awburst
	wire   [3:0] hps_0_h2f_axi_master_id_pad_m0_arregion; // hps_0_h2f_axi_master_id_pad:m0_arregion -> led_count_ip_0_s_axi_translator:s0_arregion
	wire   [0:0] hps_0_h2f_axi_master_id_pad_m0_awuser;   // hps_0_h2f_axi_master_id_pad:m0_awuser -> led_count_ip_0_s_axi_translator:s0_awuser
	wire   [7:0] hps_0_h2f_axi_master_id_pad_m0_arlen;    // hps_0_h2f_axi_master_id_pad:m0_arlen -> led_count_ip_0_s_axi_translator:s0_arlen
	wire   [3:0] hps_0_h2f_axi_master_id_pad_m0_arqos;    // hps_0_h2f_axi_master_id_pad:m0_arqos -> led_count_ip_0_s_axi_translator:s0_arqos
	wire   [3:0] hps_0_h2f_axi_master_id_pad_m0_wstrb;    // hps_0_h2f_axi_master_id_pad:m0_wstrb -> led_count_ip_0_s_axi_translator:s0_wstrb
	wire         hps_0_h2f_axi_master_id_pad_m0_wready;   // led_count_ip_0_s_axi_translator:s0_wready -> hps_0_h2f_axi_master_id_pad:m0_wready
	wire  [11:0] hps_0_h2f_axi_master_id_pad_m0_rid;      // led_count_ip_0_s_axi_translator:s0_rid -> hps_0_h2f_axi_master_id_pad:m0_rid
	wire         hps_0_h2f_axi_master_id_pad_m0_rready;   // hps_0_h2f_axi_master_id_pad:m0_rready -> led_count_ip_0_s_axi_translator:s0_rready
	wire   [7:0] hps_0_h2f_axi_master_id_pad_m0_awlen;    // hps_0_h2f_axi_master_id_pad:m0_awlen -> led_count_ip_0_s_axi_translator:s0_awlen
	wire   [3:0] hps_0_h2f_axi_master_id_pad_m0_awqos;    // hps_0_h2f_axi_master_id_pad:m0_awqos -> led_count_ip_0_s_axi_translator:s0_awqos
	wire   [3:0] hps_0_h2f_axi_master_id_pad_m0_arcache;  // hps_0_h2f_axi_master_id_pad:m0_arcache -> led_count_ip_0_s_axi_translator:s0_arcache
	wire         hps_0_h2f_axi_master_id_pad_m0_wvalid;   // hps_0_h2f_axi_master_id_pad:m0_wvalid -> led_count_ip_0_s_axi_translator:s0_wvalid
	wire  [29:0] hps_0_h2f_axi_master_id_pad_m0_araddr;   // hps_0_h2f_axi_master_id_pad:m0_araddr -> led_count_ip_0_s_axi_translator:s0_araddr
	wire   [2:0] hps_0_h2f_axi_master_id_pad_m0_arprot;   // hps_0_h2f_axi_master_id_pad:m0_arprot -> led_count_ip_0_s_axi_translator:s0_arprot
	wire   [2:0] hps_0_h2f_axi_master_id_pad_m0_awprot;   // hps_0_h2f_axi_master_id_pad:m0_awprot -> led_count_ip_0_s_axi_translator:s0_awprot
	wire  [31:0] hps_0_h2f_axi_master_id_pad_m0_wdata;    // hps_0_h2f_axi_master_id_pad:m0_wdata -> led_count_ip_0_s_axi_translator:s0_wdata
	wire         hps_0_h2f_axi_master_id_pad_m0_arvalid;  // hps_0_h2f_axi_master_id_pad:m0_arvalid -> led_count_ip_0_s_axi_translator:s0_arvalid
	wire   [3:0] hps_0_h2f_axi_master_id_pad_m0_awcache;  // hps_0_h2f_axi_master_id_pad:m0_awcache -> led_count_ip_0_s_axi_translator:s0_awcache
	wire  [11:0] hps_0_h2f_axi_master_id_pad_m0_arid;     // hps_0_h2f_axi_master_id_pad:m0_arid -> led_count_ip_0_s_axi_translator:s0_arid
	wire   [0:0] hps_0_h2f_axi_master_id_pad_m0_arlock;   // hps_0_h2f_axi_master_id_pad:m0_arlock -> led_count_ip_0_s_axi_translator:s0_arlock
	wire   [0:0] hps_0_h2f_axi_master_id_pad_m0_awlock;   // hps_0_h2f_axi_master_id_pad:m0_awlock -> led_count_ip_0_s_axi_translator:s0_awlock
	wire  [29:0] hps_0_h2f_axi_master_id_pad_m0_awaddr;   // hps_0_h2f_axi_master_id_pad:m0_awaddr -> led_count_ip_0_s_axi_translator:s0_awaddr
	wire   [1:0] hps_0_h2f_axi_master_id_pad_m0_bresp;    // led_count_ip_0_s_axi_translator:s0_bresp -> hps_0_h2f_axi_master_id_pad:m0_bresp
	wire         hps_0_h2f_axi_master_id_pad_m0_arready;  // led_count_ip_0_s_axi_translator:s0_arready -> hps_0_h2f_axi_master_id_pad:m0_arready
	wire  [31:0] hps_0_h2f_axi_master_id_pad_m0_rdata;    // led_count_ip_0_s_axi_translator:s0_rdata -> hps_0_h2f_axi_master_id_pad:m0_rdata
	wire         hps_0_h2f_axi_master_id_pad_m0_awready;  // led_count_ip_0_s_axi_translator:s0_awready -> hps_0_h2f_axi_master_id_pad:m0_awready
	wire   [1:0] hps_0_h2f_axi_master_id_pad_m0_arburst;  // hps_0_h2f_axi_master_id_pad:m0_arburst -> led_count_ip_0_s_axi_translator:s0_arburst
	wire   [2:0] hps_0_h2f_axi_master_id_pad_m0_arsize;   // hps_0_h2f_axi_master_id_pad:m0_arsize -> led_count_ip_0_s_axi_translator:s0_arsize
	wire         hps_0_h2f_axi_master_id_pad_m0_bready;   // hps_0_h2f_axi_master_id_pad:m0_bready -> led_count_ip_0_s_axi_translator:s0_bready
	wire         hps_0_h2f_axi_master_id_pad_m0_rlast;    // led_count_ip_0_s_axi_translator:s0_rlast -> hps_0_h2f_axi_master_id_pad:m0_rlast
	wire         hps_0_h2f_axi_master_id_pad_m0_wlast;    // hps_0_h2f_axi_master_id_pad:m0_wlast -> led_count_ip_0_s_axi_translator:s0_wlast
	wire   [3:0] hps_0_h2f_axi_master_id_pad_m0_awregion; // hps_0_h2f_axi_master_id_pad:m0_awregion -> led_count_ip_0_s_axi_translator:s0_awregion
	wire   [0:0] hps_0_h2f_axi_master_id_pad_m0_buser;    // led_count_ip_0_s_axi_translator:s0_buser -> hps_0_h2f_axi_master_id_pad:m0_buser
	wire   [1:0] hps_0_h2f_axi_master_id_pad_m0_rresp;    // led_count_ip_0_s_axi_translator:s0_rresp -> hps_0_h2f_axi_master_id_pad:m0_rresp
	wire  [11:0] hps_0_h2f_axi_master_id_pad_m0_awid;     // hps_0_h2f_axi_master_id_pad:m0_awid -> led_count_ip_0_s_axi_translator:s0_awid
	wire  [11:0] hps_0_h2f_axi_master_id_pad_m0_bid;      // led_count_ip_0_s_axi_translator:s0_bid -> hps_0_h2f_axi_master_id_pad:m0_bid
	wire         hps_0_h2f_axi_master_id_pad_m0_bvalid;   // led_count_ip_0_s_axi_translator:s0_bvalid -> hps_0_h2f_axi_master_id_pad:m0_bvalid
	wire   [2:0] hps_0_h2f_axi_master_id_pad_m0_awsize;   // hps_0_h2f_axi_master_id_pad:m0_awsize -> led_count_ip_0_s_axi_translator:s0_awsize
	wire         hps_0_h2f_axi_master_id_pad_m0_awvalid;  // hps_0_h2f_axi_master_id_pad:m0_awvalid -> led_count_ip_0_s_axi_translator:s0_awvalid
	wire   [0:0] hps_0_h2f_axi_master_id_pad_m0_aruser;   // hps_0_h2f_axi_master_id_pad:m0_aruser -> led_count_ip_0_s_axi_translator:s0_aruser
	wire         hps_0_h2f_axi_master_id_pad_m0_rvalid;   // led_count_ip_0_s_axi_translator:s0_rvalid -> hps_0_h2f_axi_master_id_pad:m0_rvalid

	altera_merlin_axi_translator #(
		.USE_S0_AWID                       (1),
		.USE_S0_AWREGION                   (1),
		.USE_M0_AWREGION                   (0),
		.USE_S0_AWLEN                      (1),
		.USE_S0_AWSIZE                     (1),
		.USE_S0_AWBURST                    (1),
		.USE_S0_AWLOCK                     (1),
		.USE_M0_AWLOCK                     (1),
		.USE_S0_AWCACHE                    (1),
		.USE_M0_AWCACHE                    (1),
		.USE_M0_AWPROT                     (1),
		.USE_S0_AWQOS                      (1),
		.USE_M0_AWQOS                      (0),
		.USE_S0_WSTRB                      (1),
		.USE_M0_WLAST                      (1),
		.USE_S0_BID                        (1),
		.USE_S0_BRESP                      (1),
		.USE_M0_BRESP                      (1),
		.USE_S0_ARID                       (1),
		.USE_S0_ARREGION                   (1),
		.USE_M0_ARREGION                   (0),
		.USE_S0_ARLEN                      (1),
		.USE_S0_ARSIZE                     (1),
		.USE_S0_ARBURST                    (1),
		.USE_S0_ARLOCK                     (1),
		.USE_M0_ARLOCK                     (1),
		.USE_M0_ARCACHE                    (1),
		.USE_M0_ARQOS                      (0),
		.USE_M0_ARPROT                     (1),
		.USE_S0_ARCACHE                    (1),
		.USE_S0_ARQOS                      (1),
		.USE_S0_RID                        (1),
		.USE_S0_RRESP                      (1),
		.USE_M0_RRESP                      (1),
		.USE_S0_RLAST                      (1),
		.M0_ID_WIDTH                       (12),
		.DATA_WIDTH                        (32),
		.S0_ID_WIDTH                       (12),
		.M0_ADDR_WIDTH                     (16),
		.S0_WRITE_ADDR_USER_WIDTH          (1),
		.S0_READ_ADDR_USER_WIDTH           (1),
		.M0_WRITE_ADDR_USER_WIDTH          (1),
		.M0_READ_ADDR_USER_WIDTH           (1),
		.S0_WRITE_DATA_USER_WIDTH          (1),
		.S0_WRITE_RESPONSE_DATA_USER_WIDTH (1),
		.S0_READ_DATA_USER_WIDTH           (1),
		.M0_WRITE_DATA_USER_WIDTH          (1),
		.M0_WRITE_RESPONSE_DATA_USER_WIDTH (1),
		.M0_READ_DATA_USER_WIDTH           (1),
		.S0_ADDR_WIDTH                     (30),
		.USE_S0_AWUSER                     (1),
		.USE_S0_ARUSER                     (1),
		.USE_S0_WUSER                      (1),
		.USE_S0_RUSER                      (1),
		.USE_S0_BUSER                      (1),
		.USE_M0_AWUSER                     (0),
		.USE_M0_ARUSER                     (0),
		.USE_M0_WUSER                      (0),
		.USE_M0_RUSER                      (0),
		.USE_M0_BUSER                      (0),
		.M0_AXI_VERSION                    ("AXI4"),
		.M0_BURST_LENGTH_WIDTH             (8),
		.S0_BURST_LENGTH_WIDTH             (8),
		.M0_LOCK_WIDTH                     (1),
		.S0_LOCK_WIDTH                     (1),
		.S0_AXI_VERSION                    ("AXI4")
	) led_count_ip_0_s_axi_translator (
		.aclk        (pll_0_outclk0_clk),                                     //       clk.clk
		.aresetn     (~led_count_ip_0_axi_reset_reset_bridge_in_reset_reset), // clk_reset.reset_n
		.m0_awid     (led_count_ip_0_s_axi_awid),                             //        m0.awid
		.m0_awaddr   (led_count_ip_0_s_axi_awaddr),                           //          .awaddr
		.m0_awlen    (led_count_ip_0_s_axi_awlen),                            //          .awlen
		.m0_awsize   (led_count_ip_0_s_axi_awsize),                           //          .awsize
		.m0_awburst  (led_count_ip_0_s_axi_awburst),                          //          .awburst
		.m0_awlock   (led_count_ip_0_s_axi_awlock),                           //          .awlock
		.m0_awcache  (led_count_ip_0_s_axi_awcache),                          //          .awcache
		.m0_awprot   (led_count_ip_0_s_axi_awprot),                           //          .awprot
		.m0_awvalid  (led_count_ip_0_s_axi_awvalid),                          //          .awvalid
		.m0_awready  (led_count_ip_0_s_axi_awready),                          //          .awready
		.m0_wdata    (led_count_ip_0_s_axi_wdata),                            //          .wdata
		.m0_wstrb    (led_count_ip_0_s_axi_wstrb),                            //          .wstrb
		.m0_wlast    (led_count_ip_0_s_axi_wlast),                            //          .wlast
		.m0_wvalid   (led_count_ip_0_s_axi_wvalid),                           //          .wvalid
		.m0_wready   (led_count_ip_0_s_axi_wready),                           //          .wready
		.m0_bid      (led_count_ip_0_s_axi_bid),                              //          .bid
		.m0_bresp    (led_count_ip_0_s_axi_bresp),                            //          .bresp
		.m0_bvalid   (led_count_ip_0_s_axi_bvalid),                           //          .bvalid
		.m0_bready   (led_count_ip_0_s_axi_bready),                           //          .bready
		.m0_arid     (led_count_ip_0_s_axi_arid),                             //          .arid
		.m0_araddr   (led_count_ip_0_s_axi_araddr),                           //          .araddr
		.m0_arlen    (led_count_ip_0_s_axi_arlen),                            //          .arlen
		.m0_arsize   (led_count_ip_0_s_axi_arsize),                           //          .arsize
		.m0_arburst  (led_count_ip_0_s_axi_arburst),                          //          .arburst
		.m0_arlock   (led_count_ip_0_s_axi_arlock),                           //          .arlock
		.m0_arcache  (led_count_ip_0_s_axi_arcache),                          //          .arcache
		.m0_arprot   (led_count_ip_0_s_axi_arprot),                           //          .arprot
		.m0_arvalid  (led_count_ip_0_s_axi_arvalid),                          //          .arvalid
		.m0_arready  (led_count_ip_0_s_axi_arready),                          //          .arready
		.m0_rid      (led_count_ip_0_s_axi_rid),                              //          .rid
		.m0_rdata    (led_count_ip_0_s_axi_rdata),                            //          .rdata
		.m0_rresp    (led_count_ip_0_s_axi_rresp),                            //          .rresp
		.m0_rlast    (led_count_ip_0_s_axi_rlast),                            //          .rlast
		.m0_rvalid   (led_count_ip_0_s_axi_rvalid),                           //          .rvalid
		.m0_rready   (led_count_ip_0_s_axi_rready),                           //          .rready
		.s0_awid     (hps_0_h2f_axi_master_id_pad_m0_awid),                   //        s0.awid
		.s0_awaddr   (hps_0_h2f_axi_master_id_pad_m0_awaddr),                 //          .awaddr
		.s0_awlen    (hps_0_h2f_axi_master_id_pad_m0_awlen),                  //          .awlen
		.s0_awsize   (hps_0_h2f_axi_master_id_pad_m0_awsize),                 //          .awsize
		.s0_awburst  (hps_0_h2f_axi_master_id_pad_m0_awburst),                //          .awburst
		.s0_awlock   (hps_0_h2f_axi_master_id_pad_m0_awlock),                 //          .awlock
		.s0_awcache  (hps_0_h2f_axi_master_id_pad_m0_awcache),                //          .awcache
		.s0_awprot   (hps_0_h2f_axi_master_id_pad_m0_awprot),                 //          .awprot
		.s0_awuser   (hps_0_h2f_axi_master_id_pad_m0_awuser),                 //          .awuser
		.s0_awqos    (hps_0_h2f_axi_master_id_pad_m0_awqos),                  //          .awqos
		.s0_awregion (hps_0_h2f_axi_master_id_pad_m0_awregion),               //          .awregion
		.s0_awvalid  (hps_0_h2f_axi_master_id_pad_m0_awvalid),                //          .awvalid
		.s0_awready  (hps_0_h2f_axi_master_id_pad_m0_awready),                //          .awready
		.s0_wdata    (hps_0_h2f_axi_master_id_pad_m0_wdata),                  //          .wdata
		.s0_wstrb    (hps_0_h2f_axi_master_id_pad_m0_wstrb),                  //          .wstrb
		.s0_wlast    (hps_0_h2f_axi_master_id_pad_m0_wlast),                  //          .wlast
		.s0_wvalid   (hps_0_h2f_axi_master_id_pad_m0_wvalid),                 //          .wvalid
		.s0_wuser    (hps_0_h2f_axi_master_id_pad_m0_wuser),                  //          .wuser
		.s0_wready   (hps_0_h2f_axi_master_id_pad_m0_wready),                 //          .wready
		.s0_bid      (hps_0_h2f_axi_master_id_pad_m0_bid),                    //          .bid
		.s0_bresp    (hps_0_h2f_axi_master_id_pad_m0_bresp),                  //          .bresp
		.s0_buser    (hps_0_h2f_axi_master_id_pad_m0_buser),                  //          .buser
		.s0_bvalid   (hps_0_h2f_axi_master_id_pad_m0_bvalid),                 //          .bvalid
		.s0_bready   (hps_0_h2f_axi_master_id_pad_m0_bready),                 //          .bready
		.s0_arid     (hps_0_h2f_axi_master_id_pad_m0_arid),                   //          .arid
		.s0_araddr   (hps_0_h2f_axi_master_id_pad_m0_araddr),                 //          .araddr
		.s0_arlen    (hps_0_h2f_axi_master_id_pad_m0_arlen),                  //          .arlen
		.s0_arsize   (hps_0_h2f_axi_master_id_pad_m0_arsize),                 //          .arsize
		.s0_arburst  (hps_0_h2f_axi_master_id_pad_m0_arburst),                //          .arburst
		.s0_arlock   (hps_0_h2f_axi_master_id_pad_m0_arlock),                 //          .arlock
		.s0_arcache  (hps_0_h2f_axi_master_id_pad_m0_arcache),                //          .arcache
		.s0_arprot   (hps_0_h2f_axi_master_id_pad_m0_arprot),                 //          .arprot
		.s0_aruser   (hps_0_h2f_axi_master_id_pad_m0_aruser),                 //          .aruser
		.s0_arqos    (hps_0_h2f_axi_master_id_pad_m0_arqos),                  //          .arqos
		.s0_arregion (hps_0_h2f_axi_master_id_pad_m0_arregion),               //          .arregion
		.s0_arvalid  (hps_0_h2f_axi_master_id_pad_m0_arvalid),                //          .arvalid
		.s0_arready  (hps_0_h2f_axi_master_id_pad_m0_arready),                //          .arready
		.s0_rid      (hps_0_h2f_axi_master_id_pad_m0_rid),                    //          .rid
		.s0_rdata    (hps_0_h2f_axi_master_id_pad_m0_rdata),                  //          .rdata
		.s0_rresp    (hps_0_h2f_axi_master_id_pad_m0_rresp),                  //          .rresp
		.s0_rlast    (hps_0_h2f_axi_master_id_pad_m0_rlast),                  //          .rlast
		.s0_rvalid   (hps_0_h2f_axi_master_id_pad_m0_rvalid),                 //          .rvalid
		.s0_rready   (hps_0_h2f_axi_master_id_pad_m0_rready),                 //          .rready
		.s0_ruser    (hps_0_h2f_axi_master_id_pad_m0_ruser),                  //          .ruser
		.m0_awuser   (),                                                      // (terminated)
		.m0_awqos    (),                                                      // (terminated)
		.m0_awregion (),                                                      // (terminated)
		.m0_wuser    (),                                                      // (terminated)
		.m0_buser    (1'b0),                                                  // (terminated)
		.m0_aruser   (),                                                      // (terminated)
		.m0_arqos    (),                                                      // (terminated)
		.m0_arregion (),                                                      // (terminated)
		.m0_ruser    (1'b0),                                                  // (terminated)
		.s0_wid      (12'b000000000000),                                      // (terminated)
		.m0_wid      ()                                                       // (terminated)
	);

	altera_merlin_axi_translator #(
		.USE_S0_AWID                       (1),
		.USE_S0_AWREGION                   (0),
		.USE_M0_AWREGION                   (1),
		.USE_S0_AWLEN                      (1),
		.USE_S0_AWSIZE                     (1),
		.USE_S0_AWBURST                    (1),
		.USE_S0_AWLOCK                     (1),
		.USE_M0_AWLOCK                     (1),
		.USE_S0_AWCACHE                    (1),
		.USE_M0_AWCACHE                    (1),
		.USE_M0_AWPROT                     (1),
		.USE_S0_AWQOS                      (0),
		.USE_M0_AWQOS                      (1),
		.USE_S0_WSTRB                      (1),
		.USE_M0_WLAST                      (1),
		.USE_S0_BID                        (1),
		.USE_S0_BRESP                      (1),
		.USE_M0_BRESP                      (1),
		.USE_S0_ARID                       (1),
		.USE_S0_ARREGION                   (0),
		.USE_M0_ARREGION                   (1),
		.USE_S0_ARLEN                      (1),
		.USE_S0_ARSIZE                     (1),
		.USE_S0_ARBURST                    (1),
		.USE_S0_ARLOCK                     (1),
		.USE_M0_ARLOCK                     (1),
		.USE_M0_ARCACHE                    (1),
		.USE_M0_ARQOS                      (1),
		.USE_M0_ARPROT                     (1),
		.USE_S0_ARCACHE                    (1),
		.USE_S0_ARQOS                      (0),
		.USE_S0_RID                        (1),
		.USE_S0_RRESP                      (1),
		.USE_M0_RRESP                      (1),
		.USE_S0_RLAST                      (1),
		.M0_ID_WIDTH                       (12),
		.DATA_WIDTH                        (32),
		.S0_ID_WIDTH                       (12),
		.M0_ADDR_WIDTH                     (30),
		.S0_WRITE_ADDR_USER_WIDTH          (1),
		.S0_READ_ADDR_USER_WIDTH           (1),
		.M0_WRITE_ADDR_USER_WIDTH          (1),
		.M0_READ_ADDR_USER_WIDTH           (1),
		.S0_WRITE_DATA_USER_WIDTH          (1),
		.S0_WRITE_RESPONSE_DATA_USER_WIDTH (1),
		.S0_READ_DATA_USER_WIDTH           (1),
		.M0_WRITE_DATA_USER_WIDTH          (1),
		.M0_WRITE_RESPONSE_DATA_USER_WIDTH (1),
		.M0_READ_DATA_USER_WIDTH           (1),
		.S0_ADDR_WIDTH                     (30),
		.USE_S0_AWUSER                     (0),
		.USE_S0_ARUSER                     (0),
		.USE_S0_WUSER                      (0),
		.USE_S0_RUSER                      (0),
		.USE_S0_BUSER                      (0),
		.USE_M0_AWUSER                     (1),
		.USE_M0_ARUSER                     (1),
		.USE_M0_WUSER                      (1),
		.USE_M0_RUSER                      (1),
		.USE_M0_BUSER                      (1),
		.M0_AXI_VERSION                    ("AXI4"),
		.M0_BURST_LENGTH_WIDTH             (8),
		.S0_BURST_LENGTH_WIDTH             (4),
		.M0_LOCK_WIDTH                     (1),
		.S0_LOCK_WIDTH                     (2),
		.S0_AXI_VERSION                    ("AXI3")
	) hps_0_h2f_axi_master_id_pad (
		.aclk        (pll_0_outclk0_clk),                                                    //       clk.clk
		.aresetn     (~led_count_ip_0_axi_reset_reset_bridge_in_reset_reset),                // clk_reset.reset_n
		.m0_awid     (hps_0_h2f_axi_master_id_pad_m0_awid),                                  //        m0.awid
		.m0_awaddr   (hps_0_h2f_axi_master_id_pad_m0_awaddr),                                //          .awaddr
		.m0_awlen    (hps_0_h2f_axi_master_id_pad_m0_awlen),                                 //          .awlen
		.m0_awsize   (hps_0_h2f_axi_master_id_pad_m0_awsize),                                //          .awsize
		.m0_awburst  (hps_0_h2f_axi_master_id_pad_m0_awburst),                               //          .awburst
		.m0_awlock   (hps_0_h2f_axi_master_id_pad_m0_awlock),                                //          .awlock
		.m0_awcache  (hps_0_h2f_axi_master_id_pad_m0_awcache),                               //          .awcache
		.m0_awprot   (hps_0_h2f_axi_master_id_pad_m0_awprot),                                //          .awprot
		.m0_awuser   (hps_0_h2f_axi_master_id_pad_m0_awuser),                                //          .awuser
		.m0_awqos    (hps_0_h2f_axi_master_id_pad_m0_awqos),                                 //          .awqos
		.m0_awregion (hps_0_h2f_axi_master_id_pad_m0_awregion),                              //          .awregion
		.m0_awvalid  (hps_0_h2f_axi_master_id_pad_m0_awvalid),                               //          .awvalid
		.m0_awready  (hps_0_h2f_axi_master_id_pad_m0_awready),                               //          .awready
		.m0_wdata    (hps_0_h2f_axi_master_id_pad_m0_wdata),                                 //          .wdata
		.m0_wstrb    (hps_0_h2f_axi_master_id_pad_m0_wstrb),                                 //          .wstrb
		.m0_wlast    (hps_0_h2f_axi_master_id_pad_m0_wlast),                                 //          .wlast
		.m0_wvalid   (hps_0_h2f_axi_master_id_pad_m0_wvalid),                                //          .wvalid
		.m0_wuser    (hps_0_h2f_axi_master_id_pad_m0_wuser),                                 //          .wuser
		.m0_wready   (hps_0_h2f_axi_master_id_pad_m0_wready),                                //          .wready
		.m0_bid      (hps_0_h2f_axi_master_id_pad_m0_bid),                                   //          .bid
		.m0_bresp    (hps_0_h2f_axi_master_id_pad_m0_bresp),                                 //          .bresp
		.m0_buser    (hps_0_h2f_axi_master_id_pad_m0_buser),                                 //          .buser
		.m0_bvalid   (hps_0_h2f_axi_master_id_pad_m0_bvalid),                                //          .bvalid
		.m0_bready   (hps_0_h2f_axi_master_id_pad_m0_bready),                                //          .bready
		.m0_arid     (hps_0_h2f_axi_master_id_pad_m0_arid),                                  //          .arid
		.m0_araddr   (hps_0_h2f_axi_master_id_pad_m0_araddr),                                //          .araddr
		.m0_arlen    (hps_0_h2f_axi_master_id_pad_m0_arlen),                                 //          .arlen
		.m0_arsize   (hps_0_h2f_axi_master_id_pad_m0_arsize),                                //          .arsize
		.m0_arburst  (hps_0_h2f_axi_master_id_pad_m0_arburst),                               //          .arburst
		.m0_arlock   (hps_0_h2f_axi_master_id_pad_m0_arlock),                                //          .arlock
		.m0_arcache  (hps_0_h2f_axi_master_id_pad_m0_arcache),                               //          .arcache
		.m0_arprot   (hps_0_h2f_axi_master_id_pad_m0_arprot),                                //          .arprot
		.m0_aruser   (hps_0_h2f_axi_master_id_pad_m0_aruser),                                //          .aruser
		.m0_arqos    (hps_0_h2f_axi_master_id_pad_m0_arqos),                                 //          .arqos
		.m0_arregion (hps_0_h2f_axi_master_id_pad_m0_arregion),                              //          .arregion
		.m0_arvalid  (hps_0_h2f_axi_master_id_pad_m0_arvalid),                               //          .arvalid
		.m0_arready  (hps_0_h2f_axi_master_id_pad_m0_arready),                               //          .arready
		.m0_rid      (hps_0_h2f_axi_master_id_pad_m0_rid),                                   //          .rid
		.m0_rdata    (hps_0_h2f_axi_master_id_pad_m0_rdata),                                 //          .rdata
		.m0_rresp    (hps_0_h2f_axi_master_id_pad_m0_rresp),                                 //          .rresp
		.m0_rlast    (hps_0_h2f_axi_master_id_pad_m0_rlast),                                 //          .rlast
		.m0_rvalid   (hps_0_h2f_axi_master_id_pad_m0_rvalid),                                //          .rvalid
		.m0_rready   (hps_0_h2f_axi_master_id_pad_m0_rready),                                //          .rready
		.m0_ruser    (hps_0_h2f_axi_master_id_pad_m0_ruser),                                 //          .ruser
		.s0_awid     (hps_0_h2f_axi_master_awid),                                            //        s0.awid
		.s0_awaddr   (hps_0_h2f_axi_master_awaddr),                                          //          .awaddr
		.s0_awlen    (hps_0_h2f_axi_master_awlen),                                           //          .awlen
		.s0_awsize   (hps_0_h2f_axi_master_awsize),                                          //          .awsize
		.s0_awburst  (hps_0_h2f_axi_master_awburst),                                         //          .awburst
		.s0_awlock   (hps_0_h2f_axi_master_awlock),                                          //          .awlock
		.s0_awcache  (hps_0_h2f_axi_master_awcache),                                         //          .awcache
		.s0_awprot   (hps_0_h2f_axi_master_awprot),                                          //          .awprot
		.s0_awvalid  (hps_0_h2f_axi_master_awvalid),                                         //          .awvalid
		.s0_awready  (hps_0_h2f_axi_master_awready),                                         //          .awready
		.s0_wid      (hps_0_h2f_axi_master_wid),                                             //          .wid
		.s0_wdata    (hps_0_h2f_axi_master_wdata),                                           //          .wdata
		.s0_wstrb    (hps_0_h2f_axi_master_wstrb),                                           //          .wstrb
		.s0_wlast    (hps_0_h2f_axi_master_wlast),                                           //          .wlast
		.s0_wvalid   (hps_0_h2f_axi_master_wvalid),                                          //          .wvalid
		.s0_wready   (hps_0_h2f_axi_master_wready),                                          //          .wready
		.s0_bid      (hps_0_h2f_axi_master_bid),                                             //          .bid
		.s0_bresp    (hps_0_h2f_axi_master_bresp),                                           //          .bresp
		.s0_bvalid   (hps_0_h2f_axi_master_bvalid),                                          //          .bvalid
		.s0_bready   (hps_0_h2f_axi_master_bready),                                          //          .bready
		.s0_arid     (hps_0_h2f_axi_master_arid),                                            //          .arid
		.s0_araddr   (hps_0_h2f_axi_master_araddr),                                          //          .araddr
		.s0_arlen    (hps_0_h2f_axi_master_arlen),                                           //          .arlen
		.s0_arsize   (hps_0_h2f_axi_master_arsize),                                          //          .arsize
		.s0_arburst  (hps_0_h2f_axi_master_arburst),                                         //          .arburst
		.s0_arlock   (hps_0_h2f_axi_master_arlock),                                          //          .arlock
		.s0_arcache  (hps_0_h2f_axi_master_arcache),                                         //          .arcache
		.s0_arprot   (hps_0_h2f_axi_master_arprot),                                          //          .arprot
		.s0_arvalid  (hps_0_h2f_axi_master_arvalid),                                         //          .arvalid
		.s0_arready  (hps_0_h2f_axi_master_arready),                                         //          .arready
		.s0_rid      (hps_0_h2f_axi_master_rid),                                             //          .rid
		.s0_rdata    (hps_0_h2f_axi_master_rdata),                                           //          .rdata
		.s0_rresp    (hps_0_h2f_axi_master_rresp),                                           //          .rresp
		.s0_rlast    (hps_0_h2f_axi_master_rlast),                                           //          .rlast
		.s0_rvalid   (hps_0_h2f_axi_master_rvalid),                                          //          .rvalid
		.s0_rready   (hps_0_h2f_axi_master_rready),                                          //          .rready
		.s0_awuser   (1'b0),                                                                 // (terminated)
		.s0_aruser   (1'b0),                                                                 // (terminated)
		.m0_wid      (),                                                                     // (terminated)
		.s0_awqos    (4'b0000),                                                              // (terminated)
		.s0_arqos    (4'b0000),                                                              // (terminated)
		.s0_awregion (4'b0000),                                                              // (terminated)
		.s0_arregion (4'b0000),                                                              // (terminated)
		.s0_wuser    (64'b0000000000000000000000000000000000000000000000000000000000000000), // (terminated)
		.s0_ruser    (),                                                                     // (terminated)
		.s0_buser    ()                                                                      // (terminated)
	);

endmodule
